document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("");
document.writeln("<base href=\"http://vifan.cn/\" />");
document.writeln("		<title>");
document.writeln("		维帆网");
document.writeln("		</title>");
document.writeln("");
document.writeln("    <meta name=\'description\' content=维帆是一个面向极客的站点，在这里你可以直达你的常用站点，也可以在网页上使用功能强大的一些小工具。\'\'>");
document.writeln("");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\' />");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/css/bootstrap.min.css\'>");
document.writeln("<!-- plugins -->");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/css/plugins/font-awesome.min.css\'/>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/css/plugins/simple-line-icons.css\'/>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/css/plugins/animate.min.css\'/>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/css/plugins/fullcalendar.min.css\'/>");
document.writeln("<link href=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/css/style.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("");
document.writeln("         <meta name=\'apple-mobile-web-app-capable\' content=\'yes\' />");
document.writeln("");
document.writeln("");
document.writeln("   <!--阻止Safari点击链接跳转到浏览器-->");
document.writeln("      <script charset=\'utf-8\' type=\'text/javascript\'>  if((\'standalone\' in window.navigator) && window.navigator.standalone){          var noddy, remotes = true;     document.addEventListener(\'click\', function(event) {         noddy = event.target;           while(noddy.nodeName !== \'A\' && noddy.nodeName !== \'HTML\') {             noddy = noddy.parentNode;         }         if(\'href\' in noddy && noddy.href.indexOf(\'http\') !== -1 && (noddy.href.indexOf(document.location.host) !== -1 || remotes))         {             event.preventDefault();             document.location.href = noddy.href;         }     },false); }");
document.writeln("// ]]></script>");
document.writeln("");
document.writeln("");
document.writeln("		<!--浏览器标签ico-->");
document.writeln("		<link rel=\'shortcut icon\' href=\'/favicon.ico\' />");
document.writeln("		<!--书签标签-->");
document.writeln("		<link rel=\'bookmark\' href=\'/ico.png\' />");
document.writeln("		<!--苹果桌面标题-->");
document.writeln("		<meta name=\'apple-mobile-web-app-title\' content=\'维帆网\'>");
document.writeln("		<!--苹果桌面图标-->");
document.writeln("		<link rel=\'apple-touch-icon-precomposed\' sizes=\'180x180\' href=\'/logo.png\'>");
document.writeln("	</head>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body id=\'mimin\' class=\'dashboard\'>");
document.writeln("<!-- start: Header -->");
document.writeln("<nav class=\'navbar navbar-default header navbar-fixed-top\'>");
document.writeln("  <div class=\'col-md-12 nav-wrapper\'>");
document.writeln("    <div class=\'navbar-header\' style=\'width:100%;\'>");
document.writeln("      <div class=\'opener-left-menu is-open\'> <span class=\'top\'></span> <span class=\'middle\'></span> <span class=\'bottom\'></span> </div>");
document.writeln("      <a href=\'#\' class=\'navbar-brand\'> <b>维帆网</b> </a>");
document.writeln("");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</nav>");
document.writeln("<!-- end: Header -->");
document.writeln("<div class=\'container-fluid mimin-wrapper\'>");
document.writeln("  <!-- start:Left Menu -->");
document.writeln("  <div id=\'left-menu\'>");
document.writeln("    <div class=\'sub-left-menu scroll\'>");
document.writeln("      <ul class=\'nav nav-list\'>");
document.writeln("        <li>");
document.writeln("          <div class=\'left-bg\'></div>");
document.writeln("        </li>");
document.writeln("       <li >   <a  href=\'http://vifan.cn/index.html'>  首页</a>  </li>");
document.writeln("");
document.writeln("        <li > <a  href=\'http://vifan.cn/help.html\' >帮助  </a> </li>");
document.writeln("   <li > <a class=\'tree-toggle nav-header\'> 更多  <span class=\'fa-angle-right fa right-arrow text-right\'></span> </a>");
document.writeln("          <ul class=\'nav nav-list tree\'>");
document.writeln("           <!-- <li><a href=\'list.html\'>列表</a></li>-->");
document.writeln("             <li><a href=\'https://jq.qq.com/?_wv=1027&k=5EDlld4\' target=\'");
document.writeln("_blank\'>加入Q群</a></li>");
document.writeln("");
document.writeln("            <li><a href=\'http://vifan.cn/feedback/Feedback.html\'>意见反馈</a></li>");
document.writeln("             <li><a href=\'http://vifan.cn/tool/shopweb.html\'>赞助我们</a></li>");
document.writeln("          </ul>");
document.writeln("        </li");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("     ");
document.writeln("     ");
document.writeln("     ");
document.writeln("<!-- start: Javascript --> ");
document.writeln("<script src=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/js/jquery.min.js\'></script> ");
document.writeln("<script src=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/js/jquery.ui.min.js\'></script> ");
document.writeln("<script src=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/js/bootstrap.min.js\'></script> ");
document.writeln("<!-- plugins --> ");
document.writeln("<script src=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/js/plugins/jquery.nicescroll.js\'></script> ");
document.writeln("<!-- custom --> ");
document.writeln("<script src=\'http://www.17sucai.com/preview/179632/2018-01-22/wenj.rar/asset/js/main.js\'></script> ");
document.writeln("<!-- end: Javascript -->");
